<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Skip navigation_container</name>
   <tag></tag>
   <elementGuidId>bcc1926f-c328-4860-b9b5-840fc4970422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-form > #container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='container'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4c4cd7c-03b8-4717-b4e4-157848b29676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>c42dd25e-df60-49e2-92aa-57caf9138b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-searchbox</value>
      <webElementGuid>8c94ddf4-9319-4a88-ba59-ee70e1fea505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-form&quot;)/div[@id=&quot;container&quot;]</value>
      <webElementGuid>b9fce1e8-cbf6-4ced-976f-33fada167738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='container'])[3]</value>
      <webElementGuid>b8de6213-2937-494e-97e5-e21ea0d2fd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search-form']/div</value>
      <webElementGuid>bfea7513-e39a-49f3-84af-cc43da445396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip navigation'])[1]/following::div[5]</value>
      <webElementGuid>a07455d2-688e-4bd9-b5f6-cb9713de2fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::div[7]</value>
      <webElementGuid>8defdc52-02ef-4fee-a969-e5cada34fcbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::div[9]</value>
      <webElementGuid>56518003-960f-4b7f-9da6-39748e168e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>d7599cab-ffb2-472b-94b0-51447150f11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'container']</value>
      <webElementGuid>6a22730e-c308-43ce-a73e-dc34227c247a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
